["近卫"."剑豪"]
"柏喙" = "R138"
"战车" = "RS04"
"艾丽妮" = "II07"
"陈" = "LM04"
"刻刀" = "R144"

["近卫"."强攻手"]
"布洛卡" = "SR27"
"艾丝黛尔" = "IU04"
"暴行" = "RB01"
"泡普卡" = "PA65"
"幽灵鲨" = "AA02"
"煌" = "RE41"
"百炼嘉维尔" = "RF22"

["近卫"."无畏者"]
"芙兰卡" = "BS01"
"斯卡蒂" = "AA01"
"耀骑士临光" = "KZ01"
"炎客" = "R137"
"玫兰莎" = "PA41"
"断罪者" = "MN01"
Castle-3 = "RCX3"
"缠丸" = "HK01"

["近卫"."领主"]
"拉普兰德" = "SR01"
"银灰" = "JC01"
"断崖" = "RB04"
"月见夜" = "PA62"
"芳汀" = "LT06"
"霜叶" = "R123"
"棘刺" = "II01"

["近卫"."斗士"]
"杰克" = "R166"
"因陀罗" = "GG03"
"山" = "CB05"
"燧石" = "SG06"
"猎蜂" = "US10"

["近卫"."教官"]
"鞭刃" = "KZ07"
"杜宾" = "R100"
"帕拉斯" = "MN04"
"诗怀雅" = "LM08"

["近卫"."收割者"]
"羽毛笔" = "BV13"

["近卫"."武者"]
"赫拉格" = "AZ01"
"赤冬" = "HK04"
"宴" = "HK03"

["近卫"."术战者"]
"星极" = "RR01"
"铸铁" = "R126"
"慕斯" = "VC04"
"史尔特尔" = "R111"

["近卫"."解放者"]
"龙舌兰" = "BV12"
"玛恩纳" = "KZ08"

["医疗"."疗养师"]
"清流" = "R160"
"流明" = "II09"
"絮雨" = "R163"
"锡兰" = "SS01"

["医疗"."行医"]
"蜜莓" = "RB06"
"桑葚" = "YD03"
"褐果" = "R134"

["医疗"."医师"]
"图耶" = "SG08"
"芙蓉" = "PA13"
"亚叶" = "R133"
"闪灵" = "FO01"
"苏苏洛" = "R107"
"嘉维尔" = "IU07"
"安赛尔" = "PA43"
"华法琳" = "R106"
"赫默" = "RL01"
"末药" = "R104"
"凯尔希" = "B003"
Lancet-2 = "RCX2"

["医疗"."群愈师"]
"微风" = "R132"
"白面鸮" = "RL04"
"调香师" = "MN03"
"夜莺" = "FO03"

["医疗"."咒愈师"]
"濯尘芙蓉" = "RF03"

["先锋"."尖兵"]
"嵯峨" = "HK13"
"夜刀" = "A41"
"贾维" = "SR26"
"清道夫" = "SW02"
"推进之王" = "GG01"
"香草" = "BS04"
"讯使" = "JC04"
"焰尾" = "KZ11"
"德克萨斯" = "PL02"
"凛冬" = "USS1"
"芬" = "PA11"

["先锋"."战术家"]
"夜半" = "RB12"
"豆苗" = "CB16"

["先锋"."执旗手"]
"极境" = "R131"
"桃金娘" = "R108"
"琴柳" = "VC10"

["先锋"."冲锋手"]
"风笛" = "RV02"
"野鬃" = "KZ14"
"翎羽" = "LT05"
"苇草" = "HT03"
"格拉尼" = "VC05"
"红豆" = "R105"

["先锋"."情报官"]
"晓歌" = "R143"

["术师"."轰击术师"]
"蚀清" = "CB12"
"伊芙利特" = "RL03"

["术师"."中坚术师"]
"艾雅法拉" = "LN02"
"刻俄柏" = "R155"
"史都华德" = "PA42"
"杜林" = "A44"
"特米米" = "SG05"
"夜魔" = "VC03"
"阿米娅" = "R001"
"夜烟" = "VC02"
"苦艾" = "US11"

["术师"."阵法术师"]
"薄绿" = "VC08"
"卡涅利安" = "LN04"
"蜜蜡" = "R147"

["术师"."秘术师"]
"黑键" = "LN05"
"爱丽丝" = "VC12"
"深靛" = "II05"

["术师"."扩散术师"]
"莱恩哈特" = "RB03"
"莫斯提马" = "LT77"
12F = "R303"
"格雷伊" = "R119"
"夕" = "NM02"
"天火" = "SK01"
"炎熔" = "PA15"
"远山" = "SI01"
"炎狱炎熔" = "RF01"

["术师"."链术师"]
"异客" = "SG07"
"布丁" = "CB03"
"星源" = "RL08"
"惊蛰" = "YD05"

["术师"."驭械术师"]
"卡达" = "R140"
"耶拉" = "JC00"
"澄闪" = "VC09"
"洛洛" = "VC18"
"至简" = "SG09"

["狙击"."神射手"]
"安哲拉" = "II04"
"守林人" = "ST01"
"安比尔" = "LT02"
"远牙" = "KZ13"

["狙击"."速射手"]
"流星" = "ST02"
"梅" = "VC01"
"灰喉" = "R110"
"正义骑士号" = "KZ15"
"杰西卡" = "BS03"
"四月" = "RB07"
"红云" = "R122"
"空弦" = "LT08"
"巡林者" = "A42"
"蓝毒" = "AA03"
"白金" = "KZ03"
"灰烬" = "RS01"
"能天使" = "PL03"
"安德切尔" = "PA44"
"克洛丝" = "PA12"
"寒芒克洛丝" = "RF02"

["狙击"."重射手"]
"酸糖" = "R139"
"普罗旺斯" = "SR03"
"黑" = "SS02"
"鸿雪" = "R145"

["狙击"."散射手"]
"奥斯塔" = "SR28"
"送葬人" = "LT01"
"假日威龙陈" = "R112"
"松果" = "CB09"

["狙击"."攻城手"]
"熔泉" = "VC11"
"早露" = "USS4"
"埃拉托" = "MN07"

["狙击"."炮手"]
"菲亚梅塔" = "LT11"
"白雪" = "LM10"
"慑砂" = "R158"
"陨星" = "ST03"
"空爆" = "PA63"
W = "B214"

["狙击"."投掷手"]
"迷迭香" = "RE45"
"承曦格雷伊" = "RF23"

["重装"."铁卫"]
"泡泡" = "R146"
"星熊" = "LM05"
"暴雨" = "R164"
"雷蛇" = "BS02"
"黑角" = "A43"
"可颂" = "PL04"
"卡缇" = "PA45"
"角峰" = "JC03"
"蛇屠箱" = "IU05"
"拜松" = "LM15"
"米格鲁" = "PA14"
"闪击" = "RS02"
"年" = "NM01"

["重装"."决战者"]
"森蚺" = "SG03"
"极光" = "JC09"

["重装"."驭法铁卫"]
"坚雷" = "R124"
"暮落" = "VC07"
"车尔尼" = "LN06"
"石棉" = "RB05"

["重装"."守护者"]
"瑕光" = "KZ09"
"古米" = "USS3"
"斑点" = "PA64"
"吽" = "LM19"
"临光" = "FO02"
"塞雷娅" = "RL02"

["重装"."要塞"]
"灰毫" = "KZ12"
"号角" = "VC16"

["重装"."不屈者"]
"泥岩" = "R159"
"火神" = "MN02"

["特种"."推击手"]
"温蒂" = "R117"
"食铁兽" = "YD01"
"见行者" = "LT10"
"阿消" = "LM11"

["特种"."处决者"]
"卡夫卡" = "CB06"
THRM-EX = "RCX4"
"傀影" = "R109"
"槐琥" = "LM12"
"红" = "SW01"
"砾" = "KZ04"

["特种"."傀儡师"]
"归溟幽灵鲨" = "CR02"
"贝娜" = "VC14"
"风丸" = "HK09"

["特种"."陷阱师"]
"霜华" = "RS03"
"多萝西" = "RL07"
"罗宾" = "CB08"

["特种"."钩索师"]
"雪雉" = "LM16"
"崖心" = "JC06"
"暗索" = "RB02"
"歌蕾蒂娅" = "AA05"

["特种"."伏击客"]
"狮蝎" = "SG01"
"绮良" = "HK05"
"伊桑" = "R130"
"水月" = "HK07"

["特种"."怪杰"]
"阿" = "LM20"

["特种"."行商"]
"乌有" = "YD11"
"孑" = "LM14"
"老鲤" = "LM18"

["辅助"."凝滞师"]
"梓兰" = "PA61"
"地灵" = "LN01"
"安洁莉娜" = "SR02"
"格劳克斯" = "R128"
"波登可" = "R157"
"真理" = "USS2"
"铃兰" = "R172"
"但书" = "KZ10"

["辅助"."召唤师"]
"深海色" = "AA04"
"令" = "NM03"
"麦哲伦" = "RL06"
"稀音" = "R162"
"梅尔" = "RL05"

["辅助"."吟游者"]
"海蒂" = "VC19"
"空" = "PL05"
"浊心斯卡蒂" = "CR01"

["辅助"."护佑者"]
"夏栎" = "R121"
"九色鹿" = "YD09"
"月禾" = "R129"

["辅助"."削弱者"]
"初雪" = "JC05"
"巫恋" = "R148"
"灵知" = "JC02"

["辅助"."工匠"]
"掠风" = "CB19"
"罗比菈塔" = "CB11"
