[tracker]

[inventory."D32钢"]
rarity = 5
amount = 0

[inventory."双极纳米片"]
rarity = 5
amount = 3

[inventory."聚合剂"]
rarity = 5
amount = 0

[inventory."白马醇"]
rarity = 4
amount = 0

[inventory."扭转醇"]
rarity = 3
amount = 0

[inventory."三水锰矿"]
rarity = 4
amount = 0

[inventory."轻锰矿"]
rarity = 3
amount = 0

[inventory."五水研磨石"]
rarity = 4
amount = 0

[inventory."研磨石"]
rarity = 3
amount = 0

[inventory.RMA70-24]
rarity = 4
amount = 0

[inventory.RMA70-12]
rarity = 3
amount = 0

[inventory."提纯源岩"]
rarity = 4
amount = 0

[inventory."固源岩组"]
rarity = 3
amount = 0

[inventory."固源岩"]
rarity = 2
amount = 0

[inventory."源岩"]
rarity = 1
amount = 0

[inventory."改量装置"]
rarity = 4
amount = 0

[inventory."全新装置"]
rarity = 3
amount = 0

[inventory."装置"]
rarity = 2
amount = 0

[inventory."破损装置"]
rarity = 1
amount = 0

[inventory."聚酸酯块"]
rarity = 4
amount = 0

[inventory."聚酸酯组"]
rarity = 3
amount = 0

[inventory."聚酸酯"]
rarity = 2
amount = 0

[inventory."酯原料"]
rarity = 1
amount = 0

[inventory."糖聚块"]
rarity = 4
amount = 0

[inventory."糖组"]
rarity = 3
amount = 0

[inventory."糖"]
rarity = 2
amount = 0

[inventory."代糖"]
rarity = 1
amount = 0

[inventory."异铁块"]
rarity = 4
amount = 0

[inventory."异铁组"]
rarity = 3
amount = 0

[inventory."异铁"]
rarity = 2
amount = 0

[inventory."异铁碎片"]
rarity = 1
amount = 0

[inventory."酮阵列"]
rarity = 4
amount = 0

[inventory."酮凝集组"]
rarity = 3
amount = 0

[inventory."酮凝集"]
rarity = 2
amount = 0

[inventory."双酮"]
rarity = 1
amount = 0

[inventory."聚合凝胶"]
rarity = 4
amount = 0

[inventory."凝胶"]
rarity = 3
amount = 0

[inventory."炽合金块"]
rarity = 4
amount = 0

[inventory."炽合金"]
rarity = 3
amount = 0

[inventory."晶体电子单元"]
rarity = 5
amount = 0

[inventory."晶体电路"]
rarity = 4
amount = 0

[inventory."晶体元件"]
rarity = 3
amount = 0

[inventory."精炼溶剂"]
rarity = 4
amount = 0

[inventory."半自然溶剂"]
rarity = 3
amount = 0

[inventory."切削原液"]
rarity = 4
amount = 0

[inventory."化合切削液"]
rarity = 3
amount = 0
