"微风" = "Breeze"
"星源" = "Astgenne"
"棘刺" = "Thorns"
"流明" = "Lumen"
"暮落" = "Shalem"
"红云" = "Vermeil"
"老鲤" = "Lee"
"灰毫" = "Ashlock"
"格雷伊" = "Greyy"
"泥岩" = "Mudrock"
"卡达" = "Click"
"缠丸" = "Matoimaru"
"铸铁" = "Sideroca"
"艾丝黛尔" = "Estelle"
"星熊" = "Hoshiguma"
"罗比菈塔" = "Roberta"
"翎羽" = "Plume"
"芬" = "Fang"
"夕" = "Dusk"
"絮雨" = "Whisperain"
"正义骑士号" = "\"Justice_Knight\""
"蚀清" = "Corroserum"
"乌有" = "Mr.Nothing"
"安赛尔" = "Ansel"
"地灵" = "Earthspirit"
"真理" = "Истина"
"末药" = "Myrrh"
"深靛" = "Indigo"
"焰尾" = "Flametail"
"九色鹿" = "Nine-Colored_Deer"
"空爆" = "Catapult"
"推进之王" = "Siege"
"蜜蜡" = "Beeswax"
"临光" = "Nearl"
"铃兰" = "Suzuran"
"幽灵鲨" = "Specter"
"早露" = "Роса"
"图耶" = "Tuye"
"灵知" = "Gnosis"
"吽" = "Hung"
"杜宾" = "Dobermann"
"波登可" = "Podenco"
"巡林者" = "Rangers"
"假日威龙陈" = "Ch'en_the_Holungday"
"极光" = "Aurora"
"风丸" = "Kazemaru"
"空弦" = "Archetto"
"初雪" = "Pramanix"
"苇草" = "Reed"
"阿" = "Aak"
"安哲拉" = "Andreana"
"见行者" = "Enforcer"
"赤冬" = "Akafuyu"
"炎熔" = "Lava"
"斑点" = "Spot"
"麦哲伦" = "Magallan"
"耶拉" = "Kjera"
"森蚺" = "Eunectes"
"陈" = "Ch'en"
"豆苗" = "Beanstalk"
"承曦格雷伊" = "Greyy_the_Lightningbearer"
"深海色" = "Deepcolor"
"掠风" = "Windflit"
"夜刀" = "Yato"
"年" = "Nian"
"温蒂" = "Weedy"
"夏栎" = "Quercus"
"薄绿" = "Mint"
"普罗旺斯" = "Provence"
"玫兰莎" = "Melantha"
"崖心" = "Cliffheart"
"梅尔" = "Mayer"
"褐果" = "Chestnut"
"暴雨" = "Heavyrain"
"调香师" = "Perfumer"
"布洛卡" = "Broca"
"慑砂" = "Sesa"
"莱恩哈特" = "Leonhardt"
"远牙" = "Fartooth"
"艾丽妮" = "Irene"
"月禾" = "Tsukinogi"
"迷迭香" = "Rosmontis"
"阿消" = "Shaw"
"空" = "Sora"
"讯使" = "Courier"
"黑" = "Schwarz"
"浊心斯卡蒂" = "Skadi_the_Corrupting_Heart"
"史尔特尔" = "Surtr"
"能天使" = "Exusiai"
"赫默" = "Silence"
"因陀罗" = "Indra"
"蓝毒" = "Blue_Poison"
"阿米娅" = "Amiya"
"菲亚梅塔" = "Fiammetta"
"泡泡" = "Bubble"
"帕拉斯" = "Pallas"
"芙兰卡" = "Franka"
"夜莺" = "Nightingale"
"闪击" = "Blitz"
"杰克" = "Jackie"
"刻刀" = "Cutter"
"银灰" = "SilverAsh"
"归溟幽灵鲨" = "Specter_the_Unchained"
"桑葚" = "Mulberry"
"煌" = "Blaze"
"清流" = "Purestream"
"送葬人" = "Executor"
"熔泉" = "Toddifons"
"贝娜" = "Bena"
"瑕光" = "Blemishine"
"月见夜" = "Midnight"
"凯尔希" = "Kal'tsit"
"四月" = "April"
"鞭刃" = "Whislash"
"锡兰" = "Ceylon"
"琴柳" = "Saileach"
"极境" = "Elysium"
"流星" = "Meteor"
"野鬃" = "Wild_Mane"
"洛洛" = "Rockrock"
"断崖" = "Ayerscarpe"
"梅" = "May"
"斯卡蒂" = "Skadi"
"泡普卡" = "Popukar"
"伊芙利特" = "Ifrit"
"槐琥" = "Waai_Fu"
"安比尔" = "Ambriel"
"绮良" = "Kirara"
"罗宾" = "Robin"
"霜华" = "Frost"
"水月" = "Mizuki"
"羽毛笔" = "La_Pluma"
"雷蛇" = "Liskarm"
"傀影" = "Phantom"
"艾雅法拉" = "Eyjafjalla"
"歌蕾蒂娅" = "Gladiia"
"贾维" = "Chiave"
"石棉" = "Asbestos"
"安德切尔" = "Adnachiel"
"孑" = "Jaye"
"炎客" = "Flamebringer"
"断罪者" = "Conviction"
"爱丽丝" = "Iris"
"黑角" = "Noir_Corne"
"猎蜂" = "Beehunter"
"奥斯塔" = "Aosta"
"拜松" = "Bison"
"角峰" = "Matterhorn"
"风笛" = "Bagpipe"
"桃金娘" = "Myrtle"
"蜜莓" = "Honeyberry"
"闪灵" = "Shining"
"芙蓉" = "Hibiscus"
"可颂" = "Croissant"
"白面鸮" = "Ptilopsis"
"濯尘芙蓉" = "Hibiscus_the_Purifier"
"香草" = "Vanilla"
"令" = "Ling"
"白金" = "Platinum"
"稀音" = "Scene"
"守林人" = "Firewatch"
"战车" = "Tachanka"
"澄闪" = "Goldenglow"
"柏喙" = "Bibeak"
"夜烟" = "Haze"
"食铁兽" = "FEater"
"火神" = "Vulcan"
"燧石" = "Flint"
"坚雷" = "Dur-nar"
"卡缇" = "Cardigan"
"山" = "Mountain"
"赫拉格" = "Hellagur"
"亚叶" = "Folinic"
"巫恋" = "Shamare"
"梓兰" = "Orchid"
"凛冬" = "Зима"
"霜叶" = "Frostleaf"
"耀骑士临光" = "Nearl_the_Radiant_Knight"
"莫斯提马" = "Mostima"
"龙舌兰" = "Tequila"
"芳汀" = "Arene"
"清道夫" = "Scavenger"
"酸糖" = "Aciddrop"
"杰西卡" = "Jessica"
"塞雷娅" = "Saria"
"陨星" = "Meteorite"
"灰烬" = "Ash"
"苦艾" = "Absinthe"
"蛇屠箱" = "Cuora"
"格劳克斯" = "Glaucus"
"白雪" = "ShiraYuki"
"古米" = "Гум"
"惊蛰" = "Leizi"
"格拉尼" = "Grani"
"夜魔" = "Nightmare"
"车尔尼" = "Czerny"
"灰喉" = "GreyThroat"
"嘉维尔" = "Gavial"
"克洛丝" = "Kroos"
"星极" = "Astesia"
"宴" = "Utage"
"海蒂" = "Heidi"
"诗怀雅" = "Swire"
"埃拉托" = "Erato"
"暗索" = "Rope"
"暴行" = "Savage"
"嵯峨" = "Saga"
"特米米" = "Tomimi"
"拉普兰德" = "Lappland"
"黑键" = "Ebenholz"
"米格鲁" = "Beagle"
"德克萨斯" = "Texas"
"红豆" = "Vigna"
"松果" = "Pinecone"
"红" = "Projekt_Red"
"杜林" = "Durin"
"安洁莉娜" = "Angelina"
"炎狱炎熔" = "Lava_the_Purgatory"
"狮蝎" = "Manticore"
"华法琳" = "Warfarin"
"史都华德" = "Steward"
"卡涅利安" = "Carnelian"
"刻俄柏" = "Ceobe"
"异客" = "Passenger"
"苏苏洛" = "Sussurro"
"天火" = "Skyfire"
"雪雉" = "Snowsant"
"布丁" = "Pudding"
"远山" = "Gitano"
"多萝西" = "Dorothy"
"砾" = "Gravel"
"寒芒克洛丝" = "Kroos_the_Keen_Glint"
"夜半" = "Blacknight"
"伊桑" = "Ethan"
"慕斯" = "Mousse"
"卡夫卡" = "Kafka"
"号角" = "Horn"
12F = "12F"
THRM-EX = "Thermal-EX"
W = "W"
Lancet-2 = "Lancet-2"
Castle-3 = "Castle-3"
"至简" = "Minimalist"
"晓歌" = "Cantabile"
"鸿雪" = "Позёмка"
"百炼嘉维尔" = "Gavial_the_Invincible"
"但书" = "Proviso"
"玛恩纳" = "Młynar"
