"微风" = "R132"
"星源" = "RL08"
"棘刺" = "II01"
"流明" = "II09"
"暮落" = "VC07"
"红云" = "R122"
"老鲤" = "LM18"
"灰毫" = "KZ12"
"格雷伊" = "R119"
"泥岩" = "R159"
"卡达" = "R140"
"缠丸" = "HK01"
"铸铁" = "R126"
"艾丝黛尔" = "IU04"
"星熊" = "LM05"
"罗比菈塔" = "CB11"
"翎羽" = "LT05"
"芬" = "PA11"
"夕" = "NM02"
"絮雨" = "R163"
"正义骑士号" = "KZ15"
"蚀清" = "CB12"
"乌有" = "YD11"
"安赛尔" = "PA43"
"地灵" = "LN01"
"真理" = "USS2"
"末药" = "R104"
"深靛" = "II05"
"焰尾" = "KZ11"
"九色鹿" = "YD09"
"空爆" = "PA63"
"推进之王" = "GG01"
"蜜蜡" = "R147"
"临光" = "FO02"
"铃兰" = "R172"
"幽灵鲨" = "AA02"
"早露" = "USS4"
"图耶" = "SG08"
"灵知" = "JC02"
"吽" = "LM19"
"杜宾" = "R100"
"波登可" = "R157"
"巡林者" = "A42"
"假日威龙陈" = "R112"
"极光" = "JC09"
"风丸" = "HK09"
"空弦" = "LT08"
"初雪" = "JC05"
"苇草" = "HT03"
"阿" = "LM20"
"安哲拉" = "II04"
"见行者" = "LT10"
"赤冬" = "HK04"
"炎熔" = "PA15"
"斑点" = "PA64"
"麦哲伦" = "RL06"
"耶拉" = "JC00"
"森蚺" = "SG03"
"陈" = "LM04"
"豆苗" = "CB16"
"承曦格雷伊" = "RF23"
"深海色" = "AA04"
"掠风" = "CB19"
"夜刀" = "A41"
"年" = "NM01"
"温蒂" = "R117"
"夏栎" = "R121"
"薄绿" = "VC08"
"普罗旺斯" = "SR03"
"玫兰莎" = "PA41"
"崖心" = "JC06"
"梅尔" = "RL05"
"褐果" = "R134"
"暴雨" = "R164"
"调香师" = "MN03"
"布洛卡" = "SR27"
"慑砂" = "R158"
"莱恩哈特" = "RB03"
"远牙" = "KZ13"
"艾丽妮" = "II07"
"月禾" = "R129"
"迷迭香" = "RE45"
"阿消" = "LM11"
"空" = "PL05"
"讯使" = "JC04"
"黑" = "SS02"
"浊心斯卡蒂" = "CR01"
"史尔特尔" = "R111"
"能天使" = "PL03"
"赫默" = "RL01"
"因陀罗" = "GG03"
"蓝毒" = "AA03"
"阿米娅" = "R001"
"菲亚梅塔" = "LT11"
"泡泡" = "R146"
"帕拉斯" = "MN04"
"芙兰卡" = "BS01"
"夜莺" = "FO03"
"闪击" = "RS02"
"杰克" = "R166"
"刻刀" = "R144"
"银灰" = "JC01"
"归溟幽灵鲨" = "CR02"
"桑葚" = "YD03"
"煌" = "RE41"
"清流" = "R160"
"送葬人" = "LT01"
"熔泉" = "VC11"
"贝娜" = "VC14"
"瑕光" = "KZ09"
"月见夜" = "PA62"
"凯尔希" = "B003"
"四月" = "RB07"
"鞭刃" = "KZ07"
"锡兰" = "SS01"
"琴柳" = "VC10"
"极境" = "R131"
"流星" = "ST02"
"野鬃" = "KZ14"
"洛洛" = "VC18"
"断崖" = "RB04"
"梅" = "VC01"
"斯卡蒂" = "AA01"
"泡普卡" = "PA65"
"伊芙利特" = "RL03"
"槐琥" = "LM12"
"安比尔" = "LT02"
"绮良" = "HK05"
"罗宾" = "CB08"
"霜华" = "RS03"
"水月" = "HK07"
"羽毛笔" = "BV13"
"雷蛇" = "BS02"
"傀影" = "R109"
"艾雅法拉" = "LN02"
"歌蕾蒂娅" = "AA05"
"贾维" = "SR26"
"石棉" = "RB05"
"安德切尔" = "PA44"
"孑" = "LM14"
"炎客" = "R137"
"断罪者" = "MN01"
"爱丽丝" = "VC12"
"黑角" = "A43"
"猎蜂" = "US10"
"奥斯塔" = "SR28"
"拜松" = "LM15"
"角峰" = "JC03"
"风笛" = "RV02"
"桃金娘" = "R108"
"蜜莓" = "RB06"
"闪灵" = "FO01"
"芙蓉" = "PA13"
"可颂" = "PL04"
"白面鸮" = "RL04"
"濯尘芙蓉" = "RF03"
"香草" = "BS04"
"令" = "NM03"
"白金" = "KZ03"
"稀音" = "R162"
"守林人" = "ST01"
"战车" = "RS04"
"澄闪" = "VC09"
"柏喙" = "R138"
"夜烟" = "VC02"
"食铁兽" = "YD01"
"火神" = "MN02"
"燧石" = "SG06"
"坚雷" = "R124"
"卡缇" = "PA45"
"山" = "CB05"
"赫拉格" = "AZ01"
"亚叶" = "R133"
"巫恋" = "R148"
"梓兰" = "PA61"
"凛冬" = "USS1"
"霜叶" = "R123"
"耀骑士临光" = "KZ01"
"莫斯提马" = "LT77"
"龙舌兰" = "BV12"
"芳汀" = "LT06"
"清道夫" = "SW02"
"酸糖" = "R139"
"杰西卡" = "BS03"
"塞雷娅" = "RL02"
"陨星" = "ST03"
"灰烬" = "RS01"
"苦艾" = "US11"
"蛇屠箱" = "IU05"
"格劳克斯" = "R128"
"白雪" = "LM10"
"古米" = "USS3"
"惊蛰" = "YD05"
"格拉尼" = "VC05"
"夜魔" = "VC03"
"车尔尼" = "LN06"
"灰喉" = "R110"
"嘉维尔" = "IU07"
"克洛丝" = "PA12"
"星极" = "RR01"
"宴" = "HK03"
"海蒂" = "VC19"
"诗怀雅" = "LM08"
"埃拉托" = "MN07"
"暗索" = "RB02"
"暴行" = "RB01"
"嵯峨" = "HK13"
"特米米" = "SG05"
"拉普兰德" = "SR01"
"黑键" = "LN05"
"米格鲁" = "PA14"
"德克萨斯" = "PL02"
"红豆" = "R105"
"松果" = "CB09"
"红" = "SW01"
"杜林" = "A44"
"安洁莉娜" = "SR02"
"炎狱炎熔" = "RF01"
"狮蝎" = "SG01"
"华法琳" = "R106"
"史都华德" = "PA42"
"卡涅利安" = "LN04"
"刻俄柏" = "R155"
"异客" = "SG07"
"苏苏洛" = "R107"
"天火" = "SK01"
"雪雉" = "LM16"
"布丁" = "CB03"
"远山" = "SI01"
"多萝西" = "RL07"
"砾" = "KZ04"
"寒芒克洛丝" = "RF02"
"夜半" = "RB12"
"伊桑" = "R130"
"慕斯" = "VC04"
"卡夫卡" = "CB06"
"号角" = "VC16"
12F = "R303"
THRM-EX = "RCX4"
W = "B214"
Lancet-2 = "RCX2"
Castle-3 = "RCX3"
"至简" = "Minimalist"
"晓歌" = "Cantabile"
"鸿雪" = "Позёмка"
"百炼嘉维尔" = "Gavial_the_Invincible"
"但书" = "Proviso"
"玛恩纳" = "Młynar"
bibeak = "R138"
broca = "SR27"
estelle = "IU04"
purestream = "R160"
saga = "HK13"
franka = "BS01"
corroserum = "CB12"
yato = "A41"
andreana = "II04"
lappland = "SR01"
eyjafjalla = "LN02"
bubble = "R146"
meteor = "ST02"
aciddrop = "R139"
lumen = "II09"
chiave = "SR26"
weedy = "R117"
eunectes = "SG03"
orchid = "PA61"
jackie = "R166"
dur-nar = "R124"
aosta = "SR28"
blacknight = "RB12"
skadi = "AA01"
mint = "VC08"
may = "VC01"
kafka = "CB06"
carnelian = "LN04"
specter_the_unchained = "CR02"
honeyberry = "RB06"
hoshiguma = "LM05"
blemishine = "KZ09"
ebenholz = "LN05"
toddifons = "VC11"
aurora = "JC09"
frost = "RS03"
ashlock = "KZ12"
heavyrain = "R164"
earthspirit = "LN01"
tachanka = "RS04"
indra = "GG03"
deepcolor = "AA04"
fiammetta = "LT11"
leonhardt = "RB03"
elysium = "R131"
heidi = "VC19"
passenger = "SG07"
whislash = "KZ07"
provence = "SR03"
ling = "NM03"
bagpipe = "RV02"
la_pluma = "BV13"
tuye = "SG08"
wild_mane = "KZ14"
snowsant = "LM16"
liskarm = "BS02"
pudding = "CB03"
hellagur = "AZ01"
"гум" = "USS3"
plume = "LT05"
mostima = "LT77"
click = "R140"
sora = "PL05"
12f = "R303"
greythroat = "R110"
greyy = "R119"
mountain = "CB05"
thermal-ex = "RCX4"
phantom = "R109"
executor = "LT01"
breeze = "R132"
shalem = "VC07"
schwarz = "SS02"
angelina = "SR02"
manticore = "SG01"
ceobe = "R155"
savage = "RB01"
steward = "PA42"
"\"justice_knight\"" = "KZ15"
feater = "YD01"
rosmontis = "RE45"
shirayuki = "LM10"
ptilopsis = "RL04"
kirara = "HK05"
sesa = "R158"
nearl_the_radiant_knight = "KZ01"
spot = "PA64"
irene = "II07"
quercus = "R121"
hibiscus = "PA13"
folinic = "R133"
scavenger = "SW02"
kjera = "JC00"
perfumer = "MN03"
silverash = "JC01"
siege = "GG01"
durin = "A44"
pramanix = "JC05"
"ch'en" = "LM04"
dusk = "NM02"
firewatch = "ST01"
astesia = "RR01"
noir_corne = "A43"
akafuyu = "HK04"
ambriel = "LT02"
whisperain = "R163"
bena = "VC14"
tomimi = "SG05"
waai_fu = "LM12"
croissant = "PL04"
skyfire = "SK01"
nightmare = "VC03"
dorothy = "RL07"
"ch'en_the_holungday" = "R112"
enforcer = "LT10"
meteorite = "ST03"
mudrock = "R159"
magallan = "RL06"
vanilla = "BS04"
flamebringer = "R137"
glaucus = "R128"
mulberry = "YD03"
sideroca = "R126"
courier = "JC04"
amiya = "R001"
windflit = "CB19"
jessica = "BS03"
lava = "PA15"
dobermann = "R100"
scene = "R162"
shamare = "R148"
beanstalk = "CB16"
april = "RB07"
ayerscarpe = "RB04"
czerny = "LN06"
vermeil = "R122"
archetto = "LT08"
catapult = "PA63"
hibiscus_the_purifier = "RF03"
rangers = "A42"
blue_poison = "AA03"
flametail = "KZ11"
platinum = "KZ03"
ethan = "R130"
aak = "LM20"
gitano = "SI01"
beeswax = "R147"
texas = "PL02"
utage = "HK03"
cliffheart = "JC06"
ash = "RS01"
skadi_the_corrupting_heart = "CR01"
midnight = "PA62"
flint = "SG06"
arene = "LT06"
shining = "FO01"
nine-colored_deer = "YD09"
"mr.nothing" = "YD11"
exusiai = "PL03"
gnosis = "JC02"
adnachiel = "PA44"
shaw = "LM11"
goldenglow = "VC09"
mizuki = "HK07"
"зима" = "USS1"
kroos = "PA12"
tequila = "BV12"
kazemaru = "HK09"
sussurro = "R107"
melantha = "PA41"
gavial = "IU07"
roberta = "CB11"
projekt_red = "SW01"
lava_the_purgatory = "RF01"
iris = "VC12"
ansel = "PA43"
astgenne = "RL08"
mayer = "RL05"
cardigan = "PA45"
hung = "LM19"
warfarin = "R106"
w = "B214"
myrtle = "R108"
gravel = "KZ04"
leizi = "YD05"
silence = "RL01"
reed = "HT03"
tsukinogi = "R129"
conviction = "MN01"
fartooth = "KZ13"
frostleaf = "R123"
greyy_the_lightningbearer = "RF23"
popukar = "PA65"
myrrh = "R104"
rope = "RB02"
matterhorn = "JC03"
robin = "CB08"
cuora = "IU05"
bison = "LM15"
"kal'tsit" = "B003"
thorns = "II01"
nearl = "FO02"
indigo = "II05"
haze = "VC02"
jaye = "LM14"
absinthe = "US11"
mousse = "VC04"
grani = "VC05"
surtr = "R111"
rockrock = "VC18"
vulcan = "MN02"
beehunter = "US10"
podenco = "R157"
"роса" = "USS4"
pallas = "MN04"
horn = "VC16"
specter = "AA02"
cutter = "R144"
lancet-2 = "RCX2"
castle-3 = "RCX3"
saileach = "VC10"
nightingale = "FO03"
chestnut = "R134"
kroos_the_keen_glint = "RF02"
fang = "PA11"
ifrit = "RL03"
swire = "LM08"
erato = "MN07"
saria = "RL02"
matoimaru = "HK01"
blaze = "RE41"
beagle = "PA14"
lee = "LM18"
blitz = "RS02"
"истина" = "USS2"
gladiia = "AA05"
ceylon = "SS01"
suzuran = "R172"
pinecone = "CB09"
nian = "NM01"
asbestos = "RB05"
vigna = "R105"
